### ISSUE TITLE
Glob pattern does not work on the windows platform

### ISSUE THREAD

**Issue by samyhrer** [yui/grover#1]
Giving a glob pattern such as `grover ./tests/*.html` does not work on the windows platform. Grover ends up looking for the file `./tests/*.html`, instead of a file listing of the given directory, and fails.

**Comment by davglass** [comment]
Thanks, I'll look into getting this fixed.

**Comment by samyhrer** [comment]
A pull request might have been a better approach, but I'm not all to familiar to how to contribute code to projects on Github.
I did some research by my own extended the options-module which now uses the glob-module for setting options.path. So now the test files can be run even if they are organized in a hierarchical directory structure with a pattern like ./test/*_/_.html

Relevant code

``` javascript
glob = require('glob')
....
getFiles = function(dir, pattern) {
    // Find all test files in searchPatterns.
    return glob.sync(pattern, { cwd: dir }).map(function(filepath){ return path.join(dir + "/" + filepath) });
},
...
default:
  if (v.indexOf('-') === 0) {
    console.error('Invalid option: ' + v);
    process.exit(1);
    break;
   }
   rootDir = v.substring(0, v.indexOf("/"))
   pattern = v.substring(v.indexOf("/")+1, v.length)
   options.paths = getFiles(rootDir, pattern);
```

The command would be grover ./test/**/*.html if your tests are located in the test-directory.

Thought you might find it helpful.

**Comment by davglass** [comment]
Just pushed `grover@0.0.25` with a fix for this (and a few other issues I found on Windows).
