### ISSUE TITLE
Grover should optionally combohandle local files when using --server option.

### ISSUE THREAD

**Issue by olanb7** [yui/grover#10]
It would be a nice addition if grover could serve local files via the combohandler when using the --server option.

I've forked and amended the server.js file to suit my own test purposes here: https://github.com/olanb7/grover/commit/fe0ae89a6addf925b3ae7dc2220caf9833255488 - however I'm not sure if this is already accounted for elsewhere in the tool. I'm also unsure of the best way to make this configurable.. JSON file with root:relative location mappings perhaps?

**Comment by davglass** [comment]
Grover doesn't support a JSON config file at the moment, but I could add them in as command line arguments.

``` terminal
grover --server --combo /build:./lib/build --combo /foo:./lib/foo
```

**Comment by davglass** [comment]
I've checked this in (with CLI argument support only), feel free to install master to test:

`npm install -g https://github.com/davglass/grover/archive/master.tar.gz`

**Comment by olanb7** [comment]
Works great dav, thanks!
