### ISSUE TITLE
How to let grover know about modules loader doesn't know about

### ISSUE THREAD

**Issue by Satyam** [yui/grover#12]
I'm running some tests on a few modules loader doesn't know about.  When running the individual tests, I added a `groups` entry to the `YUI({groups: xxx).use()` in the individual unit test html files but grover doesn't seem to read that and fails all tests that work fine when run individually.  How can I let it know about those dependencies?

**Comment by Satyam** [comment]
BTW: I'm using yogi and the individual tests run fine separately, I just clicked on the `run grover` option and got screens full of errors.

**Comment by davglass** [comment]
That's a yogi issue then, please file it there and include a repro case and the error output.
