### ISSUE TITLE
Test Results (TAP) are not rolled up

### ISSUE THREAD

**Issue by petey** [yui/grover#15]
Much like coverage data wasn't rolled up https://github.com/yui/grover/issues/3. The test results in most if not all formats are not rolled up in the final output.

This results in the test output only displaying the results from one of the tests, as opposed to all the different test html files.

**Comment by davglass** [comment]
Do you have an example that I can add to my tests?

**Comment by petey** [comment]
https://github.com/petey/grover_example

cd src;grover */tests/unit/index.html -o foo.tap --tap

Result (only has test results from one of the two modules):
1..9
#Begin testcase Automated Tests(0 failed of 3)
ok 1 - test one
ok 2 - test two
ok 3 - test three
#End testcase Automated Tests

Expected something like:
1..6
#Begin testcase Automated Tests(0 failed of 6)
ok 1 - test first
ok 2 - test second
ok 3 - test third
ok 4 - test one
ok 5 - test two
ok 6 - test three
#End testcase Automated Tests

**Comment by davglass** [comment]
Published in `grover@0.1.16`
