### ISSUE TITLE
Coverage: Several test pages for the same piece of javascript are not rolled up correctly

### ISSUE THREAD

**Issue by petey** [yui/grover#3]
If I have all the widget code in foo.js and several different html files with tests for different classes contained within foo.js, the coverage report is not rolled up based on the union of the test results of foo.js.

Example:
test 1 in test1.html tests Class 1 in foo.js, lines 1-50
test 2 in test2.html tests Class 2 in foo.js, lines 51-100
test 3 in test3.html tests Class 3 in foo.js lines 101-150

The result will show 33% coverage since each test only covered 33% of the code, but together all these tests cover ~100% of the code in foo.js.

**Comment by davglass** [comment]
I'll look into this and get a fix put in!

**Comment by davglass** [comment]
This should be fixed in `0.0.26`
