### ISSUE TITLE
Coverage: Need a means to produce a standard coverage report consumable by Jenkins or other coverage tool (lcov, etc) 

### ISSUE THREAD

**Issue by petey** [yui/grover#4]
Code coverage appears in some form in the json output, but does not appear in junit or any other standard format.

It's great to see the code coverage percentage on the command line, but would be even better to be able to determine which lines/functions are not covered.

**Comment by davglass** [comment]
I plan on adding that once we ditch YUITest coverage for Istanbul. The YUITest coverage tools are all in java & I don't want that headache.

**Comment by davglass** [comment]
Closed with #5.
