### ISSUE TITLE
Error when remove an iframe on teardown

### ISSUE THREAD

**Issue by Ajnasz** [yui/grover#6]
Hi,

I'm just started to use grover, and I found a bug:
If I add an iframe to the page during the test and remove it on tearDown I get the following error:

```
$ grover index.html 
Starting Grover on 1 files with PhantomJS@1.4.1
  Running 15 concurrent tests at a time.
✖ [index.html]: Passed: 0 Failed: 1 Total: 1 (ignored 0)
    Javascript Error
       Phantom failed to load this page
----------------------------------------------------------------
✖ [Total]: Passed: 0 Failed: 1 Total: 1 (ignored 0)
  [Timer] 1.275 seconds
```

Here is an example code:

https://gist.github.com/3877937

I just call grover index.html.
grover -v says: 0.0.25
node -v says: v0.8.10

I tried to track down the issue but it wasn't success. Maybe the bug is in Phantomjs but I'm not sure.
If I can help somehow, let me know.

Thanks.

**Comment by davglass** [comment]
Pushed `grover@0.0.29`.
